## Numpy Arrays and basics

Learn about Numpy


In [1]:
import numpy as np

### creating arrays from list ----


In [2]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("1d array: ", arr_1d)

arr_2d = np.array([[1, 2, 3, 4, 5],[1, 2, 3, 4, 5]])
print("2d array: ", arr_2d)

1d array:  [1 2 3 4 5]
2d array:  [[1 2 3 4 5]
 [1 2 3 4 5]]


### list VS numpy array --

In [3]:
py_list = [1, 2, 3, 4]
print("multiplication of py list: ", py_list * 2)

np_array = np.array([1, 2, 3, 4])  # element wise multiplicition
print("multiplication of numpy array: ", np_array * 2)

import time

start = time.time()
py_list = [i * 2 for i in range(100)] # for small operationa like 100 py_list can beat numpy
print("\n Python List operation time: ", time.time() - start)

start = time.time()
np_array = np.arange(100) * 2   # but for large operations like 10000000  numpy arrays are way faster than lists
print("\n np Array operation time: ", time.time() - start)


multiplication of py list:  [1, 2, 3, 4, 1, 2, 3, 4]
multiplication of numpy array:  [2 4 6 8]

 Python List operation time:  0.00033473968505859375

 np Array operation time:  8.726119995117188e-05


### Creating Arraus from scratch ---

In [4]:
# matrices are just 2d arrays

zero_s = np.zeros((3, 4))  
print("Zeros matrice: \n", zero_s)

one_s = np.ones((3, 4))
print("Ones matrice: \n", one_s)

ful_l = np.full((3, 4), 7) # create a matices with a constant value like here 7
print("full matrice: \n", ful_l)

rando_m = np.random.random((3,4)) # random is a class there are multiple methods inside random like here random()
print("random matrice: \n", rando_m)

sequence= np.arange(0,11,2)  # most used method for creating array and matrices
print("Sequence array: \n", sequence)

Zeros matrice: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones matrice: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
full matrice: 
 [[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
random matrice: 
 [[0.11351097 0.01109973 0.02497157 0.53953767]
 [0.66792081 0.34980287 0.48136957 0.07570373]
 [0.82486213 0.63968248 0.85420282 0.10442788]]
Sequence array: 
 [ 0  2  4  6  8 10]


### Vector Matrix and Tensor ---

In [5]:
vector = np.array([1, 2, 3])
print("Vector: ", vector)

matrix = np.array([[1, 2, 3], [1, 2, 3]])
print("Matrix: \n", matrix)

tensor = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("Tensor: \n", tensor)

Vector:  [1 2 3]
Matrix: 
 [[1 2 3]
 [1 2 3]]
Tensor: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array proerties ------

In [6]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Shape: ",arr.shape)
print("Dimension: ",arr.ndim)
print("Size: ",arr.size)
print("Data-Type: ",arr.dtype)


Shape:  (2, 3)
Dimension:  2
Size:  6
Data-Type:  int64


### Array Reshaping -----

In [7]:
arr = np.arange(12)
print("Origional Array: ", arr)

reshaped = arr.reshape((3, 4))
print("Reshaped Array: \n", reshaped)

flattened = reshaped.flatten()
print("Flattened Matrix: \n", flattened)

raveled = reshaped.ravel() # ravel(returns view instead of coppy)
print("Raveled Matrix: \n", raveled)

transpose=reshaped.T  # Transpose
print("Transposed Matrix: \n", transpose)

Origional Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened Matrix: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled Matrix: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed Matrix: 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
