## numpy Array operations


In [19]:
import numpy as np

### Slicing of Array


In [ ]:
arr = np.arange(11)

print("Array: ", arr)

print("Basic Slicing: ", arr[2:7])

print("With step: ", arr[1:8:2])  # takes every second element of an array

print("Nagative indexing", arr[-3])

Array:  [ 0  1  2  3  4  5  6  7  8  9 10]
Basic Slicing:  [2 3 4 5 6]
With step:  [1 3 5 7]
Nagative indexing 8


### Slicing of 2d Array


In [21]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Specific element: ", arr_2d[1, 2])  # gives 2nd element of the 1st row

print("Entire row: ", arr_2d[1])  # gives entire 1st row

print("Entire coulmn: ", arr_2d[:, 1])  # gives entire 1st column

Specific element:  6
Entire row:  [4 5 6]
Entire coulmn:  [2 5 8]


## Sorting


In [22]:
unsorted_arr = np.array([1, 6, 3, 4, 8, 5, 7, 9, 3, 2, 1])
print("Sorted array: ", np.sort(unsorted_arr))

arr_2d_unsorted = np.array([[3, 1], [1, 2], [2, 3]])
print("Unsorted 2D array: \n", arr_2d_unsorted)
print(
    "Sorted 2D array by column: \n", np.sort(arr_2d_unsorted, axis=0)
)  # 0 meams column
print("Sorted 2D array by eow: \n", np.sort(arr_2d_unsorted, axis=1))  # 1 means row

Sorted array:  [1 1 2 3 3 4 5 6 7 8 9]
Unsorted 2D array: 
 [[3 1]
 [1 2]
 [2 3]]
Sorted 2D array by column: 
 [[1 1]
 [2 2]
 [3 3]]
Sorted 2D array by eow: 
 [[1 3]
 [1 2]
 [2 3]]


## Filter


In [ ]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_numbers = numbers[numbers % 2 == 0]
print("Even Numbers: ", even_numbers)

Even Numbers:  [ 2  4  6  8 10]


### filter with mask


In [ ]:
mask = numbers > 5
print("Numbers grater than 5: ", numbers[mask])

Numbers grater than 5:  [ 6  7  8  9 10]


## Fnncy indexing V/S np.where()


In [ ]:
indices = [0, 2, 4]
print(numbers[indices])

where_results = np.where(numbers > 6)
# print(where_results)
print("Np where: ", numbers[where_results])

[1 3 5]
Np where:  [ 7  8  9 10]


In [ ]:
condition_array = np.where(numbers > 5, numbers * 2, numbers)
# This line says create an array with numbers and the elements which is grater than 5 multiply them by 2
# its like if else if(numbers>5):numbers*2  else: numbers
print("Condition array: ", condition_array)

Condition array:  [ 1  2  3  4  5 12 14 16 18 20]


## Adding and Removing data


In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

combined = np.concatenate((arr1, arr2))  # merge two arrays
print("Combined Array: ", combined)

Combined Array:  [1 2 3 4 5 6]


### Array compatiblity


In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

print("Compatiblity shape: ", a.shape == b.shape == c.shape)

Compatiblity shape:  False


### Add data through vstack and hstack

In [ ]:
origional = np.array([[1, 2], [3, 4]])

new_row = np.array([5, 6])
with_new_row = np.vstack((origional, new_row))  # adds new row
print("Origianl array: \n", origional)
print("\nWith new row: \n", with_new_row)

new_col = np.array([[7], [8]])
with_new_col = np.hstack((origional, new_col))  # adds new column
print("\nWith new column: \n", with_new_col)

Origianl array: 
 [[1 2]
 [3 4]]

With new row: 
 [[1 2]
 [3 4]
 [5 6]]

With new column: 
 [[1 2 7]
 [3 4 8]]


### remove data through .delete()

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
deleted_arr = np.delete(arr, 2)
print("Deleted array: ", deleted_arr)

arr_2d = [[1, 2], [3, 4], [5, 6]]
deleted_2d_arr = np.delete(arr_2d, 0, axis=0)  
# first argument is the array you want to delete
# second argument is the index of that row or colums
# third argument is the axis 0 for row 1 for column
print("Deleted 2d array: \n", deleted_2d_arr)

Deleted array:  [1 2 4 5]
Deleted 2d array: 
 [[3 4]
 [5 6]]
